/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MinMaxJNI */

#ifndef _Included_MinMaxJNI
#define _Included_MinMaxJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MinMaxJNI
 * Method:    findMinMax
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MinMaxJNI_findMinMax
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
